# Site settings
title: Permana
description: 'Web developer'
url: 'http://rifkycp.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Rifky Chandra Permana'
  email: rifkycp@gmail.com
  #twitter_username: joshgerdes
  facebook_username: rifkycp
  github_username:  rifkycp
  linkedin_username:  rifkycp

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
